Cargo.toml, src/server.rs
Signed-off-by: lifupan <lifupan@gmail.com>
=> ttrpc: support vsock for server

MAINTAINERS
add @teawater and @lifupan as the initial maintainers
=> add MAINTAINERS file for the project

Cargo.toml, compiler/Cargo.toml, example/Cargo.toml
=> Change authors

example/server.rs
=> Fix format issues

Cargo.toml, example/Cargo.toml
=> Change nix version to 0.16.1

example/build.rs, src/lib.rs
=> Fix tab format issue

Cargo.toml
=> Cargo.toml: Update version and homepage to update crates.io

.github/workflows/ci.yml, Makefile, src/client.rs, src/lib.rs, src/server.rs
This PR adds Github CI checks on each push/PR.
The check includes build, test, lint and formatting checks.
I also have fixed minor linter complains.
I had to suppress some linter errors, which are more complex, I plan to address those is subsequent PRs.
Signed-off-by: Maksym Pavlenko <makpav@amazon.com>
=> Add Github CI

src/channel.rs
Since the socket's recv/send would be interrupted
by signal, thus loop the recv/send until read/write
the expected lenght of data.
=> fix the issue of read/write partial msg.

README.md
=> Add instructions for code generating programmatically

Cargo.toml, src/server.rs
Add a shutdown method to Server to
shutdown the server gracefully.
=> server: add shutdown mechanism

src/server.rs
It's better to lock on the connections when do shutdown,
otherwise the connections lock would be taken first by
the server main thread and wait on child connections thread
exit, but since the shutdown couldn't take the connections
lock to close the connections, this would cause a deak lock.
BTW, when a connection closed and the dealing thread exit,
remove the connection from the server's hashmap.
=> server: fix the issue of potenial deadlock and connections leak

src/server.rs
When do server shutdown, the main thread would try to reap
the connections thread before the connections thread taking
the connections lock, which would cause a dead lock.
Using a synchronized thread to reap the exited connection
thread to avoid the potential dead lock.
Fixes: #31
=> server: reap the exited connection thread synchronously

.github/workflows/bvt.yml, .github/workflows/sanity.yml
- Add sanity checks
- Commit body check
- DCO check
- WIP check
- Clippy check
- Update old workflow
- Rename
- Do not watch pull event anymore
=> Add github workflows

Cargo.toml
=> release: v0.4.0 

src/asynchronous/mod.rs, src/lib.rs
=> Hide docs for mod async to avoid the confusion

Cargo.toml, src/asynchronous/client.rs
Return error if client does not receive response in time.
=> Async: Add support for timeout in ttrpc request

Cargo.toml
=> release: v0.4.3

Cargo.toml
=> release: v0.4.5

Cargo.toml, src/sync/server.rs
We got so many logs that we can't find valid information.
=> Change info to trace

src/sync/server.rs
1. split shutdown to shutdown_listener and shutdown_connection
2. add start_listen
Signed-off-by: quanweiZhou <quanweiZhou@linux.alibaba.com>
=> support restart server

Cargo.toml
=> release: v0.4.7

src/sync/server.rs
start_listener() -> start_listen()
shutdown_listen() -> stop_listen()
shutdown_connection() -> disconnect()
=> Change apis about server restart

Cargo.toml
=> release: v0.4.8

src/sync/client.rs, src/sync/server.rs
Since "select" would limit the monitored fd number
shouldn't be bigger than 1024, thus change it to
poll which didn't have this limit.
=> sync: change from "select" to poll

Cargo.toml
=> release: v0.4.10

Cargo.toml, compiler/Cargo.toml, compiler/README.md, ttrpc-codegen/Cargo.toml, ttrpc-codegen/README.md
- ttrpc: 0.4.14 -> 0.5.0
- ttrpc-codegen: 0.1.2 -> 0.2.0
- ttrpc-compiler: 0.3.2 -> 0.4.0
=> release: ttrpc 0.5.0, ttrpc-codegen 0.2.0, ttrpc-compiler 0.4.0

src/asynchronous/server.rs
- Return when errors found in handle_request
- Return Code::UNKNOWN(500) when handler failed
=> async-server: fix problems in handle request

src/asynchronous/server.rs
Release locks/channels in the long running handlers.
=> async server: cancel handler when client disconnected

src/asynchronous/server.rs, src/asynchronous/utils.rs
=> async-server: rework handler_request

Cargo.toml
=> release: v0.5.1

src/sync/server.rs
The sync/server uses accepted fd as key to maintain the connection and
closes the fd before client_handler thread exits. It will cause the
deadlock between listen and reaper threads. The timeline is like:
```
reaper			listener			client-handler-1
close(fd=100)
fd(=100)=accepted
start client_handler-2
locked key-values
update (100, client_handler-2)
unlocked
notify reaper fd=100
received fd=100
locked key-values
wait-client_handler-2
exit(0)
fd(=101)=accepted
acquiring lock
```
The lowest fd will be returned by accepted. The listener thread will use
new connection handler to replace the existing one. Since there is
long-running connection for container lifecycle, the reaper thread holds
the lock which listener thread is acquiring. It is deadlock.
To fix this issue, we should close fd in the …
=> sync/server: close conn fd in the reaper thread

src/server.rs
=> Fix CI for branch 0.3.0

Cargo.toml
Bump version from 0.4.15 to 0.4.16
=> release: v0.4.16

Cargo.toml, example/Cargo.toml, src/sync/server.rs, ttrpc-codegen/src/lib.rs, ttrpc-codegen/src/parser.rs
Ran `cargo audit fix` to update all crates with available security fixes.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>
=> cargo: Update dependencies identified by audit

Cargo.toml
Bump ttrpc version from 0.5.1 to 0.5.2
=> release ttrpc v0.5.2

src/asynchronous/server.rs
The async implement is wrong compared to the sync version.
This commit would fix this problem.
So that we can distinguish different connections by the `fd`
field of TtrpcContext.
=> async-server: Fill TtrpcContext with stream fd instead of listenfd

.github/workflows/bvt.yml, example/Makefile, ttrpc-codegen/Makefile, ttrpc-codegen/src/convert.rs, ttrpc-codegen/src/lib.rs, ttrpc-codegen/src/parser.rs
Add GitHub action jobs for example and ttrpc-codegen and clear ttrpc-codegen warnings.
=> Add GitHub action jobs for example and ttrpc-codegen

Cargo.toml
Release ttrpc 0.6.0
Fixes: #119
=> release: v0.6.0

src/sync/client.rs, src/sync/server.rs
Downgrade it from debug to trace.
=> sync-server: downgrade level for log "Failed to send"

src/asynchronous/client.rs
Fixes: #138
Signed-off-by: Quanwei Zhou <quanweiZhou@linux.alibaba.com>
=> asynchronous client support timeout

Cargo.toml
=> release: v0.6.1

Cargo.toml
=> release: v0.5.3

Makefile
Asynchronous features testing is required.
Signed-off-by: wllenyj <wllenyj@linux.alibaba.com>
=> ci: add --all-features to cargo test

.github/codecov.yml
Codecov annotations are annoying in code review page.
=> codecov: Add config file and disable annotations

Cargo.toml
Bump the major version due to pr #146.
=> release: v0.7.0

.github/workflows/bvt.yml, Cargo.toml, build.rs, compiler/Cargo.toml, compiler/src/codegen.rs, example/Cargo.toml, example/async-server.rs, example/build.rs, example/protocols/asynchronous/mod.rs, example/protocols/protos/health.proto, example/protocols/sync/mod.rs, example/server.rs, src/asynchronous/client.rs, src/asynchronous/stream.rs, src/asynchronous/utils.rs, src/context.rs, src/proto.rs, src/sync/client.rs, src/sync/utils.rs, ttrpc-codegen/Cargo.toml, ttrpc-codegen/src/lib.rs, ttrpc-codegen/src/model.rs, ttrpc-codegen/src/parser.rs
Includes `ttrpc`, `ttrpc-codegen`, `ttrpc-compiler`
=> Upgrade protobuf from 2.x to 3.x

build.rs, compiler/Cargo.toml
To use protobuf-codegen3@2.28.2
=> ttrpc-compiler: release v0.4.3

ttrpc-codegen/Cargo.toml
=> release ttrpc-codegen: v0.4.2

src/sync/sys/windows/net.rs
The current closing logic was causing a deadlock becuase an unused pipe was being returned when the close was called on the listenering.  This sets a flag so we can detect that we should not use that pipe connection which wasn't actually connected to a client but returned from the async call becuase we told it too.
I was using the skeleton example to test rust-extensions and found that there was a race condition when shutting the shim down. 
``` 
cargo run --example skeleton -- -namespace default -id 1234 -address "\\.\pipe\containerd-containerd"  -publish-binary ./bin/containerd start
cargo run --example shim-proto-connect \\.\pipe\containerd-shim-17630016127144989388-pipe
Connecting to \\.\pipe\containerd-shim-17630016127144989388-pipe...
Sending `Connect` request...
Connect response: …
```
=> [Windows] Closing connections properly on Windows

Cargo.toml, src/sync/server.rs, src/sync/utils.rs
Fixes: https://github.com/containerd/ttrpc-rust/issues/180
=> sync: support cancel_rx in ttrpc context

src/asynchronous/client.rs, src/asynchronous/server.rs, src/asynchronous/stream.rs, src/asynchronous/utils.rs, src/common.rs, src/error.rs, src/sync/channel.rs, src/sync/client.rs, src/sync/server.rs, src/sync/utils.rs
=> [0.5.x] Fix the bug caused by oversized packets

src/asynchronous/client.rs, src/asynchronous/connection.rs, src/asynchronous/server.rs, src/asynchronous/stream.rs, src/common.rs, src/error.rs, src/proto.rs, src/sync/channel.rs, src/sync/client.rs, src/sync/server.rs, src/sync/utils.rs
Fixes: https://github.com/containerd/ttrpc-rust/issues/198
=> [master] Fix the bug caused by oversized packets

Cargo.toml
Cut the release for PR #199 to fix issue #198.
=> ttrpc: release v0.5.5

Cargo.toml
Cut the release for #196, #197, #200, #203, #208
=> release: v0.8.1

Cargo.toml, src/asynchronous/shutdown.rs, src/lib.rs
- docs: Remove feature `protobuf-codec` which does not exist anymore
- docs: Fix the warning "unclosed HTML tag `Notifier`"
- Remove the unused dependency
=> [master] Fix docs and deps

Cargo.toml
=> ttrpc: release v0.5.7

.github/workflows/bvt.yml, Cargo.toml, Makefile, compiler/src/util.rs, rust-toolchain.toml, src/asynchronous/shutdown.rs, src/sync/sys/windows/net.rs, ttrpc-codegen/src/lib.rs, ttrpc-codegen/src/model.rs, ttrpc-codegen/src/parser.rs
It's a backport of https://github.com/containerd/ttrpc-rust/pull/223 for v0.7
=> [v0.7] Backport of "Bump rust version to resolve builds" #223

.github/workflows/cov.yml
Add token for Codecov to fixe problem:
"Rate limit reached. Please upload with the Codecov repository upload token to resolve issue"
=> [v0.7] gh-action: Fix Codecov

.github/workflows/cov.yml
Add token for Codecov to fixe problem:
"Rate limit reached. Please upload with the Codecov repository upload token to resolve issue"
=> gh-action: Fix Codecov

Cargo.toml
=> ttrpc: release v0.5.8

example/async-client.rs, src/context.rs
=> Context:optimize external interfaces

src/asynchronous/client.rs
The newest cargo fmt can detect unused code more accurate.
=> Remove the unused code

Cargo.toml
=> ttrpc: release v0.5.9

compiler/Cargo.toml, ttrpc-codegen/Cargo.toml, ttrpc-codegen/README.md
Changelog of ttrpc-compiler:
- #235
- ff13deaaf8fb9ca0e043444caed80b197f903580
Changelog of ttrpc-codegen:
- #276
- 3d3604b362ee1c4a41538a8200410e996d6cee57
=> release ttrpc-compiler@v0.7.0 and ttrpc-codegen@0.6.0

Cargo.toml
Changelog:
- #259
- #261
- #264
- #267
- #268
- #271
=> ttrpc: release v0.8.3

Cargo.toml
=> ttrpc: release v0.8.4

src/asynchronous/client.rs, src/asynchronous/connection.rs, src/asynchronous/stream.rs, src/asynchronous/utils.rs
=> stream/client: Fix early closing of socket caused by Client's lifetime

Cargo.toml
Changelog:
- #282
- #283
- #289
- #297
- #298
=> [0.8.0] ttrpc: release 0.8.5
