README.md
According to the [governance rule of containerd](https://github.com/containerd/project#non-core-project-documents),
we should clearly state this is a non-core project of containerd in 
an opening sentence.
=> Clearly state in an opening sentence

compiler/Cargo.toml
The api generated by compiler has been changed in commit 2b18b161,
but the version was forgotten to update.
This commit will fix this problem.
=> Update compiler version to 0.2.0

src/server.rs
Open the socket with SOCK_CLOEXEC to prevent socket
leak into child process.
=> open the socket with SOCK_CLOEXEC

src/server.rs
This commit add pub fn add_listener to Server.
This fn can add a fd as listener to Server.
Then user replaces fn add_listener with fn bind to provide more
flexibility for Server initialization.
=> Server: Add pub fn add_listener

src/channel.rs
When the socket peer was closed, recv will get 0 returned.
=> channel: fix the issue of missing check socket peer closed

src/server.rs
If the theads pool has been exhausted and it try to kick
the thread pool try to create another thread, but at
the same time the connection closed at the same time and
the write channel set "quit" to true which would trigge
connection dealing main thread exit, thus the control_rx
channel would be closed and the following try_send to
channel control_tx point would get an error.
=> server: fix the panic issue when client connection closed

Cargo.toml
Since the ttrpc.rs would be auto generated by protobuf, and there is no need
to hardcode the protobuf version, so revert this commit.
This reverts commit 8345ccf5741db7ccc4209ce8df7b72ed34f52166.
=> Revert "fix the issue of protobuf version mismatching issue"

src/server.rs
Add a derive attribute to make the compiler add `Debug` trait support for `TtrpcContext`. This is required to support tracing (instrumentation) for the Kata Containers rust agent, but is also a useful feature if you simply wish to print/log a context.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>
=> server: Derive Debug trait for TtrpcContext

src/common.rs
Feature sync previously incorrectly relied on sync.
This commit will fix this bug.
=> Fix feature sync actually depends on async

Cargo.toml, example/Cargo.lock, src/asynchronous/server.rs, src/common.rs, src/sync/server.rs
Vsock is different from UDS, so we cannot use UnixStream
to wrap its fd, and we should use VsockStream to do that.
=> Fix vsock in async mode

build.rs, src/lib.rs
Got:
cargo publish --dry-run
error: failed to verify package tarball
Caused by:
Source directory was modified by build.rs during cargo publish. Build scripts should not modify anything outside of OUT_DIR.
Added: /home/tim/project/ttrpc-rust/target/package/ttrpc-0.4.0/src/ttrpc.rs
This commit will resolve this issue.
=> Move generated file ttrpc.rs to OUT_DIR

Cargo.toml
Unlike in your Rust source code, we cannot use [target.'cfg(feature = "async")'.dependencies]
to add dependencies based on optional features. So we use the [features] + { optional = true } instead
=> Set dependencies of async to optional

Cargo.toml, src/lib.rs
The doc-cfg is an unstable feature, so we should use a feature flag to
turn it on.
=> Fix doc.rs

src/sync/client.rs
If client socket get error, all the client request without timeout
will hang for client receiver thread do not return the error.
Signed-off-by: quanweiZhou <edensky01@163.com>
Signed-off-by: quanweiZhou <quanweiZhou@linux.alibaba.com>
=> Bugfix: fix client request hang, for socket error.

src/sync/channel.rs
If server return an empty response, client will hang in recv msg.
=>  Bugfix: fix client request hang, for response body empty.

src/asynchronous/client.rs, src/sync/client.rs
When the client request timeout, the client would be closed
and the receive channel would be closed, thus send to it would
get an error.
=> client: fix the issue of panic when client request timeout

ttrpc-codegen/Cargo.toml, ttrpc-codegen/src/lib.rs
Also re-export the protobuf_codegen::Customize for user convienient.
=> ttrpc-codegen: fix protobuf customization unapplying

src/sync/client.rs
Change read message error type to Error::Socket
Because it's a socket error, we need to distinguish it from other errors.
Signed-off-by: quanweiZhou <quanweiZhou@linux.alibaba.com>
=> Change read message error type to Error::Socket

example/Cargo.lock, example/async-server.rs, src/asynchronous/server.rs
async: graceful shutdown and server restart supported
- Support graceful shutdown.
- Support stop_listen() -> start() to restart.
- Examples updates
- Implement AsRawFd and FromRawFd
The hot upgrade needs the restart feature.
First call stop_listen() to stop new connections coming then call
disconnect() to wait all exist request done. if there are failures
during stop_listen() and disconnect(), only need to call start()
to make rollback.
=> Graceful shutdown and server restart for async [hot upgrade needed]

Cargo.toml, src/sync/client.rs
Set close-on-exec for recver_fd, close_fd and close recver_fd after close.
=> Fix fd leakage in client

src/sync/client.rs
Instead panic, just leave a warning.
=> Log a warning when close recver_fd failed in client.

Cargo.toml, src/sync/server.rs
Since the sync channel with a buffer size of 0 will
become "rendezvous channel" where a try_send would return
directly with an error when its peer receiver isn't waiting
to acquire some data, and in this case there would be chance
to miss trigger client handler to create much more worker
threads to handle the request messages.
Thus, it should use "send" to block until its peer receiver is
available to hand off the message.
=> server: fix the issue of failed to trigger client handler

compiler/src/codegen.rs, example/Cargo.lock, example/Cargo.toml, example/async-client.rs, example/async-server.rs, example/build.rs, example/client.rs, example/server.rs, src/asynchronous/server.rs, src/asynchronous/utils.rs, src/common.rs, src/context.rs, src/lib.rs, src/sync/server.rs, src/sync/utils.rs, src/ttrpc.proto, ttrpc-codegen/Cargo.toml
For tracing purpose, it needs to pass metadata like span id to the server.
`ttrpc-rust` should then parse the metadata to service handler by `TtrpcContext`
This commit is mainly a porting of parts of `metadata_test.go`
and `types.go` if go version, and now only working on server side.
Signed-off-by: bin liu <bin@hyper.sh>
=> api: add metadata for server and client

src/context.rs
Users can easily use it without manually clone it.
Signed-off-by: bin <bin@hyper.sh>
=> Add Clone derive for Context

example/async-client.rs, src/asynchronous/client.rs, src/asynchronous/server.rs
- Support timeout on server side.
- Remove timeout on client side.
- Update example
=> Add server timeout, remove client timeout

src/lib.rs
The #![rustfmt::skip] we used in ttrpc.rs has been
marked as soft_unstable in rust 1.52(rust-lang/rust#82399)
So we would got a build error like
`error: custom inner attributes are unstable`
This commit will fix this issue.
=> Allow soft_unstable lint

Cargo.toml, src/asynchronous/server.rs
tokio-vsock 0.3.1 has fixed the fd leak to child process
problem(rust-vsock/vsock-rs#15), upgrade the tokio-vsock
and remove the set-cloexec hack for the tokio-vsock stream.
=> Bump tokio-vsock to 0.3.1 and remove hack code for it

example/async-client.rs, example/client.rs, src/asynchronous/client.rs, src/common.rs, src/error.rs, src/sync/client.rs
In current implementation `Client` must be created from `RawFd` handle.
This forces crate users to import `nix` dependency in their projects just to create a Client instance.
So this PR adds a shortcut `Client::connect(path)` to make it more user friendly.
Signed-off-by: Maksym Pavlenko <pavlenko.maksym@gmail.com>
=> Add client connect

src/common.rs
The suffix does not obey the protocol.
Fixes: containerd#98
=> Remove redundant path suffix of unix domain socket

compiler/Cargo.toml, compiler/src/prost_codegen.rs
Let's move to version 0.8 to obtain latest fixes. cargo-audit identified
issues with the current version, including:
RUSTSEC-2020-0002
RUSTSEC-2021-0073
Signed-off-by: Eric Ernst <eric_ernst@apple.com>
=> cargo: update prost dependencies

.github/workflows/bvt.yml, Cargo.toml, compiler/src/codegen.rs, src/asynchronous/server.rs, src/common.rs, src/sync/channel.rs, src/sync/client.rs, src/sync/server.rs
This PR adds MacOS support to TTRPC rust crate.
It uses conditional compilation to exclude vsock on non Linux platforms.
And another difference is that MacOS doesn't support creation of a descriptor with `CLOEXEC` atomically, so this PR adds `fcntl` calls after.
client/server example running on MacOS:
<details>
```
Compiling ttrpc-example v0.2.0 (/Users/mxpv/Github/ttrpc-rust/example)
Finished dev [unoptimized + debuginfo] target(s) in 4.58s
Running `/Users/mxpv/Github/ttrpc-rust/target/debug/examples/server`
[00:00:00.000] (10d15f600) INFO   server listen started
[00:00:00.000] (10d15f600) INFO   server started
Server is running, press Ctrl + C to exit
[00:00:17.822] (700001891000) DEBUG  Got new client
[00:00:17.822] (700001e9a000) TRACE  Got Message header MessageHeader { length: 91, …
```
=> Support MacOS

src/sync/server.rs
The sync/server uses accepted fd as key to maintain the connection and
closes the fd before client_handler thread exits. It will cause the
deadlock between listen and reaper threads. The timeline is like:
```
reaper			listener			client-handler-1
close(fd=100)
fd(=100)=accepted
start client_handler-2
locked key-values
update (100, client_handler-2)
unlocked
notify reaper fd=100
received fd=100
locked key-values
wait-client_handler-2
exit(0)
fd(=101)=accepted
acquiring lock
```
The lowest fd will be returned by accepted. The listener thread will use
new connection handler to replace the existing one. Since there is
long-running connection for container lifecycle, the reaper thread holds
the lock which listener thread is acquiring. It is deadlock.
To fix this issue, we should close fd in the …
=> [release/0.4] sync/server: close conn fd in the reaper thread

.github/workflows/bvt.yml, deny.toml
`cargo-deny` is a popular Rust tool to lint project's dependencies to make sure they meet expectations.
It can track dependencies without license, with vulnerabilities, deprecated, yanked, etc.
Links:
- https://github.com/EmbarkStudios/cargo-deny
- https://github.com/EmbarkStudios/cargo-deny-action
- https://embarkstudios.github.io/cargo-deny/
Example:
```
┌─ /Users/mxpv/Github/ttrpc-rust/Cargo.lock:8:1
│
8 │ nix 0.16.1 registry+https://github.com/rust-lang/crates.io-index
│ ---------------------------------------------------------------- security vulnerability detected
│
= ID: RUSTSEC-2021-0119
= Advisory: https://rustsec.org/advisories/RUSTSEC-2021-0119
= On certain platforms, if a user has more than 16 groups, the
`nix::unistd::getgrouplist` function will call the libc `getgrouplist` …
```
=> Add cargo deny to CI

compiler/Cargo.toml
Bump ttrpc-compiler from 0.4.0 to 0.4.1
to fix RUSTSEC-2020-0002, RUSTSEC-2021-0073
Fixes: #113 
=> release ttrpc-compiler v0.4.1

Cargo.toml, example/Cargo.toml, src/sync/channel.rs
Updated the `nix` crate to the latest version as this allows `errno`
handling to be simplified.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>
=> cargo: Update nix crate

src/asynchronous/stream.rs, src/common.rs, src/sync/channel.rs, src/sync/client.rs
To let Linux os use normal Unix domain socket, this commit
extends the Domain enum and control the socket type by
the address pattern passed in:
- vsock://xxx:xx          -> Vsock
- unix:///run/aaa.sock    -> normal Unix domain sock
- unix://@/run/abc.sock   -> abstract Unix sock
- other:///run/d.sock     -> error
Fixes: #115
Signed-off-by: bin liu <bin@hyper.sh>
=> add support for normal Unix domain socket

compiler/src/codegen.rs
This is a sub-PR of #118. For detailed discussion, please see the original PR.
This updates the compiler, so that it generates code that could make async requests via a `&XxxClient` instead of `&mut XxxClient`.
=> Allow concurrent usage of the asynchronous Client (part 1/2)

compiler/Cargo.toml, compiler/README.md
Release ttrpc-compiler 0.5.0
We need bump the major version because of #123
=> ttrpc-compiler: release v0.5.0

ttrpc-codegen/Cargo.toml, ttrpc-codegen/README.md
Release ttrpc-codegen 0.3.0 to bump
ttrpc-compiler from 0.4.0 to 0.5.0
=> ttrpc-codegen: release v0.3.0

example/async-client.rs, src/asynchronous/client.rs
Currently, the `request()` method of `ttrpc::r#async::Client` takes an `&mut self`. This prevents the `Client` from being used concurrently, since a mutable reference in Rust indicates (and enforces) exclusive use of an object.
In this patch, we change the signature of `request()` to take `&self` instead of `&mut self`. This allows multiple coroutines to issue concurrent RPC requests via the same `Client` object (e.g. by using an `Arc`), without breaking the API compatibility (although most of existing code will generate a warning indicating that a `let mut` is unnecessary).
We see (in the example code) that this problem is currently worked around by cloning the `Client`. However, we still hope to propose this patch, since by avoiding cloning the `Client`, we could improve the performance …
=> Allow concurrent usage of the asynchronous Client (part 2/2)

src/asynchronous/client.rs, src/asynchronous/server.rs, src/asynchronous/utils.rs, src/common.rs, src/error.rs, src/lib.rs, src/sync/client.rs, src/sync/server.rs, src/sync/utils.rs, ttrpc-codegen/README.md
This commit add doc for soket address, and change function
parameters from host/path to sockaddr.
Also make some unnecessary functions from public to private.
Signed-off-by: bin liu <bin@hyper.sh>
=> crate: add doc for socket address

example/async-client.rs, example/async-server.rs, example/client.rs, example/server.rs
In #116, we update the protocol of socket path to
- vsock://xxx:xx -> Vsock
- unix:///run/aaa.sock -> normal Unix domain sock
- unix://@/run/abc.sock -> abstract Unix sock
- other:///run/d.sock -> error
In the example we use abstract socket, so we should
update the address "unix:///tmp/1" to "unix://@/tmp/1".
=> example: Use new domain socket protocol of ttrpc

Cargo.toml
The dependency protobuf is required for ttrpc now. so the
feature flag protobuf-codec is useless.
=> 0.6.0-prepare: remove feature flag protobuf-codec

example/async-client.rs, example/async-server.rs, example/client.rs, example/server.rs, example/utils.rs
Because macOS does not support abstract unix socket address.
=> example: use path socket address to support macOS

src/asynchronous/client.rs, src/error.rs
Previously, socket errors (such as connection reset or early EOF) were not properly handled in `ttrpc::r#async::Client`: https://github.com/containerd/ttrpc-rust/blob/e5a5373ca13270b608457944be231ccc71adf756/src/asynchronous/client.rs#L137-L140
If such errors were occurred during an RPC, the resources associated with the RPC (i.e. its sender channel) will become leaked (i.e. never being used or dropped), causing the RPC to hang forever, which is not what we want in an erroneous condition.
This patch tries to properly deliver socket errors to all pending RPC callers, as well as add some log messages useful for debugging.
Note that there are some side effects caused by this patch:
1. The `ttrpc::Error` type now becomes `Clone`able, since we want to deliver the error to all pending RPC …
=> Improve handling of socket errors in the async client

src/asynchronous/stream.rs, src/common.rs, src/error.rs, src/sync/channel.rs
Now aync/async can use the same code to parse MessageHeader.
Signed-off-by: wllenyj <wllenyj@linux.alibaba.com>
=> Improve MessageHeader parsing.

Cargo.toml
=> deps: remove unused crate bytes

ttrpc-codegen/src/parser.rs
Got:
error: called `.err().expect()` on a `Result` value
--> src/parser.rs:2193:46
|
2193 |         let err = FileDescriptor::parse(msg).err().expect("err");
|                                              ^^^^^^^^^^^^ help: try: `expect_err`
|
= note: `-D clippy::err-expect` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#err_expect
This commit fixes this problem.
=> ttrpc-codegen: Fix clippy warnings about expect_err

compiler/src/codegen.rs, deny.toml, example/Cargo.toml, example/Makefile, example/async-stream-client.rs, example/async-stream-server.rs, example/build.rs, example/protocols/asynchronous/mod.rs, example/protocols/protos/streaming.proto, src/asynchronous/client.rs, src/asynchronous/connection.rs, src/asynchronous/mod.rs, src/asynchronous/server.rs, src/asynchronous/shutdown.rs, src/asynchronous/stream.rs, src/asynchronous/utils.rs, src/common.rs, src/error.rs, src/lib.rs, src/proto.rs, src/sync/channel.rs, src/sync/client.rs, src/sync/server.rs, src/sync/utils.rs, ttrpc-codegen/Cargo.toml
Introduce support for streaming(https://github.com/containerd/ttrpc/blob/main/PROTOCOL.md#streaming). This is already supported by Golang's TTRPC in https://github.com/containerd/ttrpc/pull/107. But currently only async is implemented. Related issues #144.
This pull request changes include:
1. Improved message encoding and decoding.
2. Added `shutdown` module to handle graceful shutdown.
3. Refactored connection handling.
4. Added streaming support, and added an example about streaming.
Usually, streaming supports 3 types:
* Server streaming
* Client streaming
* Bidirectional streaming ( or duplex streaming )
These 3 types are the same as GRPC, see https://grpc.io/docs/what-is-grpc/core-concepts/#server-streaming-rpc for details.
A general `Bidirectional streaming` process is as follows: …
=> Streaming support.

src/asynchronous/stream.rs, src/proto.rs
Fix following clippy warnings caused by new added clippy-rules in rust 1.63.
```
error: you are deriving `PartialEq` and can implement `Eq`
--> src/proto.rs:31:39
|
31 | #[derive(Default, Debug, Clone, Copy, PartialEq)]
|                                       ^^^^^^^^^ help: consider deriving `Eq` as well: `PartialEq, Eq`
|
= note: `-D clippy::derive-partial-eq-without-eq` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq
error: you are deriving `PartialEq` and can implement `Eq`
--> src/asynchronous/stream.rs:323:30
|
323 | #[derive(Clone, Copy, Debug, PartialEq)]
|                              ^^^^^^^^^ help: consider deriving `Eq` as well: `PartialEq, Eq`
|
= help: for further …
```
=> clippy: fix warnings in rust 1.63

compiler/Cargo.toml, compiler/README.md, ttrpc-codegen/Cargo.toml, ttrpc-codegen/README.md
Because https://github.com/containerd/ttrpc-rust/pull/146 introduces incompatible changes, we should bump the major version of `ttrpc-compiler`.  and because we bump the dependency `ttrpc-compiler` in `ttrpc-codegen`, we should bump the major version of `ttrpc-codegen` too.
=> Release ttrpc-compiler v0.6.0 and ttrpc-codegen v0.4.0

Cargo.toml, compiler/Cargo.toml, example/Cargo.toml, ttrpc-codegen/Cargo.toml, ttrpc-codegen/src/parser.rs
Optional field was not generated right by protobuf-codegen-pure3@2.27.3.
I have fixed the problem on version 2.28.1, so we can bump the protobuf-codegen-pure3 to 2.28.1 to fix the problem.
=> [0.5.0] ttrpc-codegen: Fix proto3's optional support

Cargo.toml, compiler/Cargo.toml, example/Cargo.toml, ttrpc-codegen/Cargo.toml, ttrpc-codegen/src/parser.rs
Optional field was not generated right by protobuf-codegen-pure3@2.27.3.
I have fixed the problem on version 2.28.1, so we can bump the protobuf-codegen-pure3 to 2.28.1 to fix the problem.
=> [0.6.0] ttrpc-codegen: Fix proto3's optional support

Cargo.toml, src/asynchronous/server.rs, src/common.rs, src/sync/server.rs
AOSP has vsock support via the cuttlefish hypervisor. This PR enables vsock functionality on android, in addition to linux.
=> Android support

build.rs, src/asynchronous/client.rs, src/asynchronous/stream.rs, src/proto.rs, src/sync/client.rs, ttrpc-codegen/src/convert.rs, ttrpc-codegen/src/lib.rs, ttrpc-codegen/src/parser.rs
Fixes needless borrow error from #165 
```
error: the borrowed expression implements the required traits
--> build.rs:17:17
|
17 |         .inputs(&["src/ttrpc.proto"])
|                 ^^^^^^^^^^^^^^^^^^^^ help: change this to: `["src/ttrpc.proto"]`
|
= note: `-D clippy::needless-borrow` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
error: could not compile `ttrpc` due to previous error
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:29: check] Error 101
Error: Process completed with exit code 2.
```
Signed-off-by: Austin Vazquez <macedonv@amazon.com>
=> ttrpc: fix lint errors in build

.github/workflows/bvt.yml
* Updated actions/checkout from v2 to v3.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
Related issue: https://github.com/containerd/project/issues/95
Signed-off-by: Austin Vazquez <macedonv@amazon.com>
=> Update GitHub actions packages

src/asynchronous/client.rs, src/asynchronous/server.rs, src/asynchronous/stream.rs, src/asynchronous/utils.rs, src/common.rs, src/sync/channel.rs, src/sync/client.rs, src/sync/server.rs, ttrpc-codegen/src/convert.rs, ttrpc-codegen/src/parser.rs
Fixes linter by running `cargo clippy --fix --all-features` after updating to latest rust tool chain with `rustup update stable` which is run in CI.
Fixes building from main branch:
```bash
make 
cargo build --verbose --all-targets
Compiling ttrpc v0.7.1 (/home/jstur/projects/ttrpc-rust)
error: variables can be used directly in the `format!` string
--> src/common.rs:27:34
|
27 |           return Err(Error::Others(format!(
|  __________________________________^
28 | |             "failed to set listener fd: {} as non block: {}",
29 | |             listener, e
30 | |         )));
| |_________^
|
....
```
=> Clippy Fixes for latest rust (1.67)

.github/workflows/bvt.yml, Makefile, compiler/Makefile, compiler/src/codegen.rs, compiler/src/util.rs, example/Makefile
ci: Separate CI testing to Check and Build
Disable the duplicated CI testing named "Clippy Check", and separate the Build action into two parts: "Check" and "Build".
Signed-off-by: Xuewei Niu <niuxuewei.nxw@antgroup.com>
=> ci: Separate CI testing to Check and Build

.github/workflows/bvt.yml, Cargo.toml, Makefile, example/async-client.rs, example/async-server.rs, example/async-stream-client.rs, example/async-stream-server.rs, example/build.rs, example/client.rs, example/protocols/mod.rs, example/utils.rs, src/asynchronous/client.rs, src/asynchronous/stream.rs, src/common.rs, src/error.rs, src/lib.rs, src/macros.rs, src/sync/channel.rs, src/sync/client.rs, src/sync/mod.rs, src/sync/server.rs, src/sync/sys/mod.rs, src/sync/sys/unix/mod.rs, src/sync/sys/unix/net.rs, src/sync/sys/windows/mod.rs, src/sync/sys/windows/net.rs, src/sync/utils.rs, tests/sync-test.rs
Fixes: #132 
This PR adds initial support for Windows.  The scope is fairly large, so it only adds support for `sync` implementation to keep it fairly reasonable 😬. It would be possible to split out some parts of the work into smaller PR's or commits as needed. I have two main commits but happy to make them more distinct.  It also has all the changes from #171 so I can drop those once that merges 👍 
Note: I am fairly new to Rust so might need some guidance on choices I made here. There is still some more work to be done (adding security file descriptors to named pipe for instance) in the PR but wanted to get it open for discussion on the general direction.
This PR does three main things:
- moves unix specific calls out of the main server and client functions.  It does this by introducing …
=> Windows Support for Sync implementation

src/sync/client.rs
When adding windows implementation the new_client call had a possibility of failing so the result was wrapped in a Result<Client>. This caused the existing api to use a unwrap_or_else and panic since we couldn't pass the result onto the user.
=> Add new api for creating client

src/error.rs, src/sync/sys/windows/net.rs
The `unwrap()` on the file when creating the client connection causes a panic.  This can happen if the file doesn't exist or there is a small chance when multiple clients connect quickly that the pipe returns 'All pipe instances are busy.' also causing a panic.  This allows the caller to handle these errors and retry if necessary (as is the case with the pipe instances being busy).
=> [Windows] Check for errors when connecting with client

MAINTAINERS
Tim Zhang(@Tim-Zhang) has meaningful contribution to the project and is
the maintainer of project as collaborator. He should be added as member
officially. I'd like to add him as COMMITTER.
And Lei Wang(@wllenyj) has been a active reviewer, but he is still
collaborator. He should be added as member as well. So, I'd like to add
him as REVIEWER.
Needs explicit LGTM from:
Signed-off-by: Wei Fu <fuweid89@gmail.com>
---------
@containerd/committers @teawater @lifupan
=> MAINTAINERS: add Tim Zhang and Lei Wang as member

src/sync/sys/windows/net.rs
When using raw_os_error it will return Some() if it is an OS error otherwise it will return None and the error isn't related to OS failure. This handles it there won't be a panic in the case of a non OS error.
feedback based on https://github.com/containerd/ttrpc-rust/pull/185#discussion_r1176725294.  Will need to rebase/update this once #182 #185 merge
=> [windows] Unwrap error as windows error or otherwise return error message

Cargo.toml, src/common.rs
Updates the dependencies for the main ttrpc project.  This is in preparation for a release to include the Windows files in support for projects like the rust shim in https://github.com/containerd/rust-extensions/pull/139
=> Update dependencies for the main ttrpc project

src/sync/client.rs
When introducing Windows support the client creation resulted in a Result<Client> being returned. This a breaking update for client::new in the client API.
Follow up to https://github.com/containerd/ttrpc-rust/pull/181 and https://github.com/containerd/ttrpc-rust/pull/190#issuecomment-1576001447
=> Update client::new to return Result<Client>

Cargo.toml
Release ttrpc: v0.8.0. The main feature of this release is support for the Windows Synchronous server and client
This allows usage in projects like https://github.com/containerd/rust-extensions/pull/139
I don't know the projects release process but was hoping to start the conversation here.  I am happy to help document the process as well. 
Leaving in draft until #189 merges
=> Release ttrpc: v0.8.0

src/asynchronous/server.rs
the listener fd is not closed after the server shutdown, this will make a residual socket fd in the process if it is running different servers again and again.
here I changed the example codes to reproduce it:
```
// Copyright (c) 2020 Ant Financial
//
// SPDX-License-Identifier: Apache-2.0
//
#[macro_use]
extern crate log;
use std::sync::Arc;
#[cfg(unix)]
use async_trait::async_trait;
use log::LevelFilter;
#[cfg(unix)]
use tokio::signal::unix::{signal, SignalKind};
use tokio::time::sleep;
#[cfg(unix)]
use protocols::r#async::{agent, agent_ttrpc, health, health_ttrpc, types};
#[cfg(unix)]
use ttrpc::asynchronous::Server;
use ttrpc::error::{Error, Result};
use ttrpc::proto::{Code, Status};
mod protocols;
mod utils;
struct HealthService;
#[cfg(unix)]
#[async_trait]
impl health_ttrpc::Health …
```
=> async: Close listener fd after server shutdown

src/asynchronous/mod.rs
=> stream: public stream related types

example/async-stream-client.rs, example/async-stream-server.rs, example/protocols/protos/streaming.proto, src/asynchronous/client.rs, src/asynchronous/server.rs
Protobuf encodes default values, e.g., 0 for number, "" for string, as empty payload and we wouldn't send empty payload to a receiver.
This commit change the method of empty message detecting.
Fixes #169
Fixes #207
=> stream: Fix default data won't be received issue

Cargo.toml, src/asynchronous/shutdown.rs, src/lib.rs
- docs: Remove feature `protobuf-codec` which does not exist anymore
- docs: Fix the warning "unclosed HTML tag `Notifier`"
- Remove the unused dependency
=> [0.7.0] Fix docs and deps

src/sync/server.rs
When running on MacOs we found a bug:
```
Dec 12 18:45:42 spin-oci-worker containerd[102]: time="2023-12-12T18:45:42.523982005Z" level=info msg="Shim successfully started, waiting for exit signal..."
Dec 12 18:45:42 spin-oci-worker containerd[102]: time="2023-12-12T18:45:42.533327005Z" level=error msg="listener accept got Os { code: 4, kind: Interrupted, message: "Interrupted system call" }"
Dec 12 18:45:42 spin-oci-worker containerd[102]: time="2023-12-12T18:45:42.535132005Z" level=info msg="ttrpc server listener stopped"
```
This will retry the connection.  I don't have a Mac to test this on but wanted to open it up for feedback incase others are seeing the error
=> Handle OS Interruptions

.github/workflows/bvt.yml, Cargo.toml, Makefile, compiler/src/util.rs, rust-toolchain.toml, src/asynchronous/shutdown.rs, src/sync/sys/windows/net.rs, ttrpc-codegen/src/lib.rs, ttrpc-codegen/src/model.rs, ttrpc-codegen/src/parser.rs
Fixes #219 
Switches to using https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
=> Bump rust version to resolve builds

src/sync/sys/unix/net.rs
Android target fails to compile as fd is not defined.
=> Fix android build

src/asynchronous/server.rs
The async implementation doesn't wait for responses to be sent to clients when shutting down. These responses are lost if the application exists fast enough before the write task gets to send them. That means that the response for a request that triggers shutdown of the server might be lost without the client knowing that the server was actually stopped.
I observed this behavior in kata-containers. The kata shim sends `DestroySandboxRequest` request to kata-agent, which runs inside the VM, to tell it to clean up and exit. The handler code for this request sets an event to tell the main thread that the process can be stopped. After that it returns an empty response to the shim. The main thread calls ttrpc_server_obj.shutdown() and the process exits. The ttrpc shutdown code doesn't wait for …
=> send all pending responses before shutting down

src/sync/server.rs
If the Accept error occurs, an error can be output to ensure that the subsequent connect can be accepted normally.
Fixes: #239
=> server: fix server exit once a accept failed

src/asynchronous/client.rs, src/asynchronous/connection.rs, src/asynchronous/server.rs, src/asynchronous/stream.rs
Currently the send() method of stream implemented by send the value to an unbounded channel, so even the connection is closed for a long time, the send function still return succeed.
In this PR I add a channel to the message so that we can wait until the message is truely written to the connection.
=> Fix the stream sending reliability

compiler/src/codegen.rs, example/Cargo.toml, example/async-client.rs, example/async-server.rs, example/async-stream-client.rs, example/async-stream-server.rs, example/protocols/mod.rs, example/server.rs
This commit changes the generated ttrpc server from Arc<Box<T>> to Arc<T>. This helps the type conversion and also avoids extra runtime cost caused by double pointer.
Fixes #234
=> Codegen: convert Arc<Box<T>> to Arc<T>

src/sync/sys/unix/net.rs
It should be a mistake to modify it from -1 to 10
in the PR #226
https://github.com/containerd/ttrpc-rust/pull/226/files#diff-e74ddb472174f24fb4713f5a2fe2d33bbc5db28ee2a5c7dad1ea9025b897e8a5R110
There already are monitor_fd to notify exit, so accept without timeout is safe.
=> Update timeout to infinite for poll of accept

src/asynchronous/shutdown.rs
This patch fixes a hang that can occur in wait_all_exit().
self.wait() without await returns a Future, so the notified() object is not created until we await on the returned future.  That means notify_waiters() can be called before notified() is. This leads to notified() waiting forever because notify_waiters is called only once, when the last waiter is dropped.
notify_waiters() and notified() form a happens-before relationship. There are two possible scenarios:
1. If notified() comes before notify_waiters() this means we can safely await on notified().
2. If notified() comes after notify_waiters() this means that what happened before it is visible in the notified() thread. Waiting on notified() at this point will block but we can check for waiters count, which is guaranteed to be 0 …
=> Fix hang in wait_all_exit

src/asynchronous/server.rs
The stream request and data is handle asynchronously, if the data is handled when stream is not created yet, the data will be discarded and an error occur.
we should wait until the stream is created and then the subsequent message can be handled.
=> fix timing issue of streaming

src/asynchronous/client.rs
The error type shuld more friendly to external interfaces
=> async:when the client request failed. Learn from ttrpc-go

compiler/src/codegen.rs
Refactor codegen.rs to use write_line instead of field_entry for client initialization.
An example of this:
```
warning: redundant field names in struct initialization
--> xxx_ttrpc.rs
|
|             client: client,
|             ^^^^^^^^^^^^^^ help: replace it with: `client`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_field_names
= note: `#[warn(clippy::redundant_field_names)]` on by default
```
=> clippy: fix warnings for redundant field names in struct initialization

src/asynchronous/server.rs
1、Modify the unit of measurement for timeout
2、Add clearly error message
3、Add Check if it is already shutdown no need select in handle_msg
=> Optimize some code in async server.rs

Cargo.toml, compiler/Cargo.toml, src/common.rs, ttrpc-codegen/Cargo.toml
Parse vsock cid and port from address("vsock://cid:port").
Fixes: #266
=> vsock: parse cid from vsock

ttrpc-codegen/src/lib.rs
If not set out_dir,it will use env 'OUT_DIR' to generate proto rs file.You can use 'include!' marco to include env 'OUT_DIR' proto rs .
And you needn't to create a dir in your source dir.
=> Add default out_dir support

src/sync/server.rs
Since poll is level-triggered, an uncorrected error can lead to an infinite loop, so we sleep for a while and wait for the error to be corrected.
Fixes: #270
=> sync-server: Fix infinite loop caused by accept error

example/async-stream-client.rs, example/async-stream-server.rs, example/protocols/protos/streaming.proto
Add example for server_send_stream to show server how to use stream send data to client.
=> examples: Add example for server_send_stream

src/sync/server.rs
Also Add the method set_accept_retry_interval.
Since poll is level-triggered, an uncorrected error can lead to an infinite loop, so we sleep for a while and wait for the error to be corrected.
Fixes: #270
=> [v0.5]  sync-server: Fix infinite loop caused by accept erro

compiler/src/codegen.rs, rust-toolchain.toml, ttrpc-codegen/src/lib.rs, ttrpc-codegen/src/parser.rs
Update rust version from 1.77.0
=> Use rust 1.81.0 to develop

ttrpc-codegen/Cargo.toml
Fixes: https://github.com/stepancheg/rust-protobuf/pull/733
=> ttrpc-codegen: bump protobuf-codegen to 3.5.1

src/common.rs
With Linux 6.12, specifically this commit:
https://github.com/torvalds/linux/commit/5b0af621c3f6ef9261cf6067812f2fd9943acb4b, one can not call `setsockopt(2)` on non-inet (`AF_INET`/`AF_INET6`) sockets anymore. As the ttRPC socket can only ever be non-inet, we should not ever call `setsockopt(2)` here.
=> Do not setsockopt(2) on AF_UNIX / AF_VSOCK sockets

compiler/src/codegen.rs
Got follow build issue with a service that doesn't have normal methods and just has stream methods:
error: variable does not need to be mutable
-->
/home/t4/teawater/coco/kata-containers/src/libs/protocols/src/attestation_agent_ttrpc.rs:60:9
|
60 |     let mut methods = HashMap::new();
|         ----^^^^^^^
|         |
|         help: remove this `mut`
|
= note: `-D unused-mut` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(unused_mut)]`
The reason is the code that generate from proto file is:
let mut methods = HashMap::new();
let mut streams = HashMap::new();
streams.insert("ContainerEventsStream".to_string(),
Arc::new(ContainerEventsStreamMethod{service:
service.clone()}) as Arc<dyn ::ttrpc::r#async::StreamHandler + Send + Sync>); …
=> compiler: write_async_server_create: Fix no methods mut issue

src/sync/client.rs, src/sync/sys/unix/net.rs
Fixed issue where reaching the file descriptor limit (EMFILE) during ClientConnection creation could lead to unexpected process termination.
=> Bugfix: fix panic caused by fd limit reached during new ClientConnection

src/asynchronous/server.rs
Break the accepting-new-connection loop correctly when the server object was dropped.
Fixes: #284
=> async/server: Fix the the dropping of the server object

.github/workflows/bvt.yml, deny.toml, src/sync/server.rs
We need to ensure that only when the connection is successfully inserted into the connections map can the handler send fd to notify the reaper to recycle the connection.
Otherwise, the handler may have been executed and sent fd to notify the reaper to recycle the connection, and the connection has not been inserted into the map. Then the reaper cannot find the corresponding connection after receiving the fd, and loses the opportunity to recycle the connection, causing fd leakage;
=> sync: fix the connection fd leak on the server side

Cargo.toml, RELEASE.md, compiler/Cargo.toml, example/Cargo.toml, example/protocols/mod.rs, ttrpc-codegen/Cargo.toml
This PR adds a workspace to the repo to simplify dependency management and crate publishing.
=> Add a workspace
